version: "3.8"

volumes:
  prometheus_vol:

networks:
  prometheus-network:

services:
  app01:
    depends_on:
      - prometheus
    build:
      context: health
    labels:
      app: health_check_1
      env: production
    environment:
      PORT: ${APP01:-9091}
    networks:
      - prometheus-network

  app02:
    depends_on:
      - prometheus
    build:
      context: health
    labels:
      app: health_check_2
      env: production
    environment:
      PORT: ${APP02:-9092}
    networks:
      - prometheus-network

  app03:
    depends_on:
      - prometheus
    build:
      context: health
    labels:
      app: health_check_3
      env: test
    environment:
      PORT: ${APP03:-9093}
    networks:
      - prometheus-network

  prometheus:
    image: bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    working_dir: "/opt/bitnami/prometheus/conf"
    environment:
      DOCKER_CONTENT_TRUST: 1
    command: ["--web.config.file", "web-config.yml"]
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - "prometheus_vol:/opt/bitnami/prometheus/data"
      - "./configs/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"
      - "./configs/prometheus-rules.yml:/opt/bitnami/prometheus/conf/prometheus-rules.yml"
      - "./configs/web-config.yml:/opt/bitnami/prometheus/conf/web-config.yml"
      - "./configs/psw.txt:/opt/bitnami/prometheus/conf/prometheus_psw.txt"
      - "./certs/server.crt:/opt/bitnami/prometheus/conf/server.crt"
      - "./certs/server.key:/opt/bitnami/prometheus/conf/server.key"
    networks:
      - prometheus-network
