global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus-rules.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['localhost:9090']
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: john
      password_file: 'prometheus_psw.txt'

  # Go Health Job
  - job_name: 'go-health'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: [ 'app01:9091', 'app02:9092' ]
        labels:
          group: 'production'

      - targets: [ 'app03:9093' ]
        labels:
          group: 'canary'
