# TLS and basic authentication configuration example.

# Additionally, a certificate and a key file are needed.
tls_server_config:
  cert_file: server.crt
  key_file: server.key

# Usernames and passwords required to connect to Prometheus.
# Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
basic_auth_users:
  john: $2y$10$bN4MzG02Ie0iFjsfcjHfueplqdtuDsLMYrvE.eh87..mxSpyY1.iG