groups:
  - example:
    rules:
      # The name of the alert. Must be a valid label value.
      alert: <string>

      # The PromQL expression to evaluate. Every evaluation cycle this is
      # evaluated at the current time, and all resultant time series become
      # pending/firing alerts.
      expr: <string>

      # Alerts are considered firing once they have been returned for this long.
      # Alerts which have not yet fired for long enough are considered pending.
        [ for: <duration> | default = 0s ]

      # How long an alert will continue firing after the condition that triggered it
      # has cleared.
        [ keep_firing_for: <duration> | default = 0s ]

      # Labels to add or overwrite for each alert.
      labels:
        [ <labelname>: <tmpl_string> ]

      # Annotations to add to each alert.
      annotations:
        [ <labelname>: <tmpl_string> ]


# ----------------------- Example -----------------------
# groups:
#   - name: example
#     rules:
#       - alert: HighRequestLatency
#         expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
#         for: 10m
#         labels:
#           severity: page
#         annotations:
#           summary: High request latency



# ----------------------- Other examples -----------------------
# groups:
#   - name: example
#     rules:
#
#       Alert for any instance that is unreachable for >5 minutes.
#       - alert: InstanceDown
#         expr: up == 0
#         for: 5m
#         labels:
#           severity: page
#         annotations:
#           summary: "Instance {{ $labels.instance }} down"
#           description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
#
#       Alert for any instance that has a median request latency >1s.
#       - alert: APIHighRequestLatency
#         expr: api_http_request_latencies_second{quantile="0.5"} > 1
#         for: 10m
#         annotations:
#           summary: "High request latency on {{ $labels.instance }}"
#           description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"